#
# Get ghdl and run all the test benches
#
language: C

sudo: required
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - mkdir ghdl
  - wget https://github.com/tgingold/ghdl/releases/download/2016-05-03/ghdl-0.34dev-mcode-2016-05-03.tgz -O - | tar xz -C ghdl
  - sudo apt-get update -qq
  - sudo apt-get -y install libgnat-4.6

script:
  - source bin/env.sh
  - export PATH=$PWD/ghdl/bin:$PATH
  - cd tb
  - ghdl-all.sh

after_failure:
  - VERBOSE=1 ghdl-all.sh
