#
# Get ghdl and run all the test benches
#
language: C

sudo: false
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

env:
  -

cache:
    directories:
      - $HOME/ghdl
      - $HOME/lib

before_install:
  - travis/deps.sh

script:
  - export PATH=$HOME/ghdl/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
  - source bin/env.sh
  - cd tb
  - ghdl-all.sh

after_failure:
  - VERBOSE=1 ghdl-all.sh
