#
# Get ghdl and run all the test benches
#
language: C

sudo: false
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

env:
  -

cache:
    directories:
      - $HOME/ghdl
      - $HOME/lib

before_install:
  - .travis/deps.sh

script:
  - .travis/tb.sh
  - .travis/codingstyle.sh

after_failure:
  - VERBOSE=1 .travis/tb.sh